name: Check my markdown for deadlinks

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15

      - run: gh issue create --title "Deadlinks in markdown detected" --body "Check error logs\:\ https://github.com/johnlokerse/github-cli-demo/actions/runs/${{ vars.GITHUB_RUN_ID }}"
        if: failure()
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}