name: Check my markdown for deadlinks

on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 0 */2 * *"
    workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15

      - run: gh issue create --title "Deadlinks in markdown detected" --body "Check error log for deadlink(s):\ ${{ github.SERVER_URL }}/${{ github.REPOSITORY }}/actions/runs/${{ github.RUN_ID }}"
        if: failure()
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_RUN_ID: ${{ vars.GITHUB_RUN_ID }}