name: List my Resource Groups in a GitHub Issue

on:
    workflow_dispatch:

jobs:
  create-issue:
    runs-on: windows-latest

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRET }}

      - name: Run create-resources.sh
        uses: Azure/CLI@v1
        with:
          azcliversion: 2.48.1
          inlineScript: |
            az group list --query "[?contains(name, 'github')]" --output table > groups
            gh issue create --title "Resource group overview" --body-file groups